### ISSUE TITLE
login docs

### ISSUE THREAD

**Issue by CouldBeThis** [Darkle/Roffline#2]
Just noting that the readme [says](https://github.com/Darkle/Roffline#security) there is a login and the landing page seems to want a login but username admin is not allowed. However in the other tab "signup":

> Roffline doesn't use passwords, but rather unique usernames.
> 
> Copy the username below & save it. Then click the signup button.

which works.

P.S. This is Issue № 1 but there are `1000` commits in the repo. that is a lot of work! 
![image](https://user-images.githubusercontent.com/53547181/156277224-260068c5-5d6e-43fb-b009-da17f97f5c7c.png)

**Comment by Darkle** [comment]
Hi, the admin login is actually for a special admin section which can be found via your settings page. Sorry for the confusion. I have update the readme to clarify: https://github.com/Darkle/Roffline#security
